-- ══════════════════════════════════════════════════════════
-- Star Aesthetic Centre — ISDIN Product Descriptions
-- 5 products · Full 8-section template
-- Generated: 2026-04-02
-- ══════════════════════════════════════════════════════════

-- 1. ISDIN Fusion Water Magic SPF50 (untinted)
update public.products set description = $desc$
<h3>Is ISDIN Fusion Water Magic SPF50 right for you?</h3>
<ul>
<li><strong>Anyone who dislikes the feel of sunscreen</strong> — The water-light texture is so invisible and weightless that patients who have never worn SPF daily become consistent wearers within a week.</li>
<li><strong>Oily and combination skin</strong> — The oil-free formula absorbs instantly with zero residue, leaving skin matte and comfortable from morning to evening.</li>
<li><strong>Post-treatment patients needing daily SPF</strong> — Lightweight enough to layer after Botox, fillers, Dermapen or peels without any heaviness or irritation on freshly treated skin.</li>
<li><strong>Active patients and outdoor enthusiasts</strong> — Can be applied directly onto wet skin — after swimming, sweating or water activities — making reapplication practical for the first time.</li>
<li><strong>All skin tones in the South African climate</strong> — Leaves absolutely no white cast and no greasiness even in peak Durban summer heat and humidity.</li>
</ul>

<h3>How ISDIN Fusion Water Magic SPF50 works — the science</h3>
<p>ISDIN's proprietary <strong>Fusion Water technology</strong> encapsulates SPF50 broad-spectrum UVA and UVB filters in an ultra-fine aqueous suspension that behaves like water on contact with skin — the micro-droplets burst instantly and deposit a uniform, invisible protective film without any oil phase to create drag, heaviness or pore congestion. The <strong>photostable filter system</strong> maintains full SPF50 efficacy from application through to reapplication, resisting degradation from UV exposure and perspiration. A built-in <strong>antioxidant complex</strong> neutralises the free radicals generated by UV and environmental exposure that topical SPF filters alone cannot intercept, addressing the full oxidative pathway of photoageing in a single product.</p>

<h3>What you will notice — and when</h3>
<p><strong>Immediately:</strong> Applies like water, disappears in seconds. Skin feels exactly like itself — clean, comfortable and completely uncoated. No white cast, no stickiness, no scent.<br><strong>Week 1–2:</strong> You stop noticing you are wearing SPF. The product removes every sensory barrier to daily compliance — patients who have avoided sunscreen for years wear this without hesitation.<br><strong>Month 1+:</strong> Consistent daily broad-spectrum protection prevents the incremental UV damage that accumulates into fine lines, pigmentation and uneven texture. Treatment results last measurably longer when protected every day.</p>

<h3>How to use ISDIN Fusion Water Magic SPF50</h3>
<ol>
<li>Apply as the final step of your morning skincare routine, after serum and any treatment products.</li>
<li>Dispense a generous amount and smooth evenly across face, neck and décolletage — do not under-apply as this reduces the SPF level.</li>
<li>Makeup can be applied immediately — the instant-dry formula creates a smooth, receptive base.</li>
<li>Reapply every 2 hours during sun exposure. Uniquely, this formula can be applied directly onto wet skin after swimming or exercise — no need to dry off first.</li>
</ol>

<h3>Key ingredients &amp; what they do</h3>
<table>
<tr><th>Ingredient</th><th>What it does for you</th></tr>
<tr><td>Fusion Water Technology</td><td>ISDIN's proprietary delivery system — encapsulates UV filters in an ultra-fine aqueous suspension that absorbs like water, leaving no oily residue or white cast on any skin tone.</td></tr>
<tr><td>UVA/UVB Broad-Spectrum Filters</td><td>Photostable chemical filters provide SPF50 protection against both burning UVB rays and the deeper, ageing UVA rays that penetrate cloud cover and glass.</td></tr>
<tr><td>Antioxidant Complex</td><td>Neutralises UV-generated free radicals that escape the filter barrier, preventing the oxidative cascade that drives photoageing and pigmentation independently of UV.</td></tr>
<tr><td>Oil-Free Aqueous Base</td><td>Non-comedogenic, hypoallergenic, biodegradable vehicle that delivers actives without any pore-clogging oil phase — safe for even the most acne-prone skin.</td></tr>
<tr><td>Water-Resistant Film Formers</td><td>Allow the formula to be applied on wet skin and maintain protection during water activities — a practical advantage no standard sunscreen lotion can match.</td></tr>
</table>

<h3>Dr. Bangalee's clinical perspective</h3>
<table>
<tr><td><strong>Dr. Bangalee Recommends</strong></td><td>"The Fusion Water Magic is the sunscreen I recommend for patients who have been resistant to daily SPF because of texture. Nothing else I have found comes close to its feel — it genuinely disappears on contact. For my post-treatment patients who need to protect their investment, the fact that it can be applied on wet skin also makes reapplication realistic for active patients in our climate." — Dr. Rajeev Bangalee, MB BS</td></tr>
</table>

<h3>What our patients say</h3>
<table>
<tr>
<td>"I have never worn sunscreen consistently in my life. This is the first one that actually feels like nothing. I apply it every morning now without even thinking about it." — Jason, 38</td>
<td>"After my Dermapen treatments Dr. Bangalee insisted on daily SPF. The Fusion Water is so light I forget I have it on. My skin has healed beautifully." — Naledi, 34</td>
<td>"I surf most mornings and reapplying sunscreen was always a hassle. Being able to apply this on wet skin has completely changed my routine." — Brett, 29</td>
</tr>
</table>

<h3>Frequently asked questions</h3>
<table>
<tr><td><strong>Can I really apply this on wet skin?</strong></td><td>Yes — this is one of ISDIN Fusion Water Magic's most distinctive features. The aqueous formula bonds to skin even in the presence of water, making it the most practical reapplication option for swimmers, surfers and anyone who sweats heavily.</td></tr>
<tr><td><strong>Does it leave a white cast?</strong></td><td>No — the formula contains no mineral filters (zinc oxide or titanium dioxide), so it is completely transparent on all skin tones including the deepest complexions. If you want tinted coverage, choose the Light, Medium or Bronze variants.</td></tr>
<tr><td><strong>Is it suitable for acne-prone skin?</strong></td><td>Yes — the oil-free, non-comedogenic, hypoallergenic formula has been specifically tested for acne-prone and sensitive skin. It is one of the safest daily SPF options for patients with active breakouts.</td></tr>
<tr><td><strong>Can I use it after a skin treatment?</strong></td><td>Yes — its lightweight, oil-free formula makes it an excellent post-procedure SPF. For very reactive skin immediately after Dermapen or chemical peels, Dr. Bangalee may recommend a 100% mineral option for the first 48–72 hours, after which the Fusion Water can be used.</td></tr>
<tr><td><strong>How does this compare to the tinted variants?</strong></td><td>The untinted Fusion Water Magic is completely clear — ideal for patients who already wear foundation or who prefer a no-makeup look. The Light, Medium and Bronze variants add a skin-tone-matching tint that provides light coverage and can replace foundation on its own.</td></tr>
</table>
$desc$, updated_at = now() where slug = 'isdin-fusion-water-magic-spf50';

-- 2. ISDIN Fusion Water Magic Light SPF50
update public.products set description = $desc$
<h3>Is ISDIN Fusion Water Magic Light right for you?</h3>
<ul>
<li><strong>Fair to light skin tones wanting SPF + coverage in one step</strong> — The Light shade is calibrated for Fitzpatrick types I–II, providing a sheer, natural finish that evens skin tone without any visible makeup look.</li>
<li><strong>Patients who want to simplify their morning routine</strong> — Replace foundation, moisturiser and SPF with one product. The Light tint covers mild redness and uneven tone while delivering full SPF50 protection.</li>
<li><strong>Post-pigmentation or post-peel patients with lighter skin</strong> — Covers residual discolouration from treatment while the SPF50 prevents new UV-triggered pigmentation forming.</li>
<li><strong>Active patients who want coverage that survives movement</strong> — The Fusion Water formula stays on through perspiration and can be reapplied on wet skin — coverage that actually holds during a South African summer.</li>
<li><strong>Anyone who dislikes the feel of tinted moisturisers</strong> — The water-light texture is nothing like a traditional tinted moisturiser — it absorbs in seconds and sits completely invisibly on the skin.</li>
</ul>

<h3>How ISDIN Fusion Water Magic Light works — the science</h3>
<p>The <strong>Light tint variant</strong> delivers the identical ISDIN Fusion Water technology as the untinted formula — encapsulating SPF50 UVA and UVB filters in an ultra-fine aqueous suspension — but adds <strong>cosmetic-grade mineral pigments</strong> calibrated to fair-to-light skin tones that deposit a sheer, natural-looking colour correction layer as the aqueous base evaporates. The pigments are suspended in the same water-phase vehicle, meaning the tint applies as evenly and invisibly as the clear formula. The <strong>photostable filter system</strong> maintains full SPF50 efficacy through perspiration, and the unique wet-skin application capability means the tinted protection layer can be refreshed during water activities without disrupting coverage.</p>

<h3>What you will notice — and when</h3>
<p><strong>Immediately:</strong> A sheer, natural warmth that evens your skin tone instantly. The Light tint enhances rather than masks — skin looks like itself but better.<br><strong>Week 1–2:</strong> Morning routine shortens significantly. Foundation use drops — many patients use the Light as their only face product on weekdays.<br><strong>Month 1+:</strong> Consistent daily SPF50 protection prevents the UV damage that creates new pigmentation and deepens fine lines. Combined with Dr. Bangalee's treatments, results are maintained far more effectively.</p>

<h3>How to use ISDIN Fusion Water Magic Light</h3>
<ol>
<li>Apply after your morning skincare routine as the final step — this is your SPF and your coverage in one.</li>
<li>Dispense and spread evenly across the face using fingertips, blending outward to the hairline and jaw for a seamless finish.</li>
<li>Allow 20–30 seconds to set before applying any additional makeup if desired.</li>
<li>Reapply every 2 hours in the sun. The wet-skin application capability means you can reapply directly after swimming — a genuine advantage in the KZN summer.</li>
</ol>

<h3>Key ingredients &amp; what they do</h3>
<table>
<tr><th>Ingredient</th><th>What it does for you</th></tr>
<tr><td>Fusion Water Technology</td><td>ISDIN's ultra-fine aqueous suspension that delivers SPF and tint simultaneously in a water-light base — absorbs in seconds with no white cast, no greasiness and no makeup feel.</td></tr>
<tr><td>Light Shade Mineral Pigments</td><td>Cosmetic-grade pigments calibrated for fair to light skin tones — provide sheer, natural colour correction that evens skin tone without the opacity of traditional foundation.</td></tr>
<tr><td>SPF50 UVA/UVB Filters</td><td>Photostable broad-spectrum filters maintain full protection throughout the day and through perspiration — protecting both against burning and the deeper ageing UV wavelengths.</td></tr>
<tr><td>Antioxidant Complex</td><td>Intercepts the free radicals generated by UV and environmental exposure that escape the filter barrier, completing the photoprotection picture beyond what SPF alone provides.</td></tr>
<tr><td>Oil-Free Non-Comedogenic Base</td><td>Zero oil phase means zero pore congestion, zero midday shine and zero breakouts — the tinted coverage does not come at the cost of skin comfort.</td></tr>
</table>

<h3>Dr. Bangalee's clinical perspective</h3>
<table>
<tr><td><strong>Dr. Bangalee Recommends</strong></td><td>"For my lighter-skinned patients who want everything in one morning product, the Fusion Water Light is exceptional. The tint is subtle enough to look completely natural but does a genuine job of evening the complexion. I particularly like recommending it to patients post-peel or post-Dermapen — it gives them the SPF protection they need with the coverage to feel confident while their skin finishes healing." — Dr. Rajeev Bangalee, MB BS</td></tr>
</table>

<h3>What our patients say</h3>
<table>
<tr>
<td>"I used to spend 20 minutes on my morning skincare. Now I apply this and I am done. The coverage is natural and my skin is protected. I cannot believe it took me this long to find it." — Claire, 41</td>
<td>"After my chemical peel my skin was still a little uneven. Dr. Bangalee suggested the Light and it covers beautifully while protecting at the same time. Genius product." — Mariska, 36</td>
<td>"The most natural finish I have found in an SPF. People think I am wearing foundation but I am not. Just this, every morning." — Lindi, 33</td>
</tr>
</table>

<h3>Frequently asked questions</h3>
<table>
<tr><td><strong>What skin tones does Light suit?</strong></td><td>The Light shade is calibrated for fair to light skin tones (Fitzpatrick types I–II). For medium skin tones, the Medium variant provides a better colour match. For deeper complexions, the Bronze variant is recommended.</td></tr>
<tr><td><strong>Can I skip foundation entirely?</strong></td><td>Many patients do. The sheer coverage evens skin tone and covers mild redness beautifully for everyday use. For special occasions or higher-coverage needs, it makes an excellent base under foundation.</td></tr>
<tr><td><strong>Is it suitable after skin treatments?</strong></td><td>Yes — the lightweight, oil-free formula is well-tolerated post-procedure. For the first 48 hours after Dermapen or chemical peels, Dr. Bangalee may prefer a 100% mineral SPF before transitioning to the Fusion Water Light.</td></tr>
<tr><td><strong>Will it transfer onto clothing or a mask?</strong></td><td>Minimal transfer — the Fusion Water formula dries to a light-hold finish that resists transfer better than traditional tinted moisturisers. Reapplication may be needed after mask wearing.</td></tr>
<tr><td><strong>How does this compare to the Heliocare Color Gel?</strong></td><td>Both are tinted SPF50 gels. The Fusion Water Light uses ISDIN's wet-skin technology and has an exceptionally water-like texture. The Heliocare Color Gel offers stronger mattifying with sebum-absorbing polymers. Both are excellent — Dr. Bangalee will guide you based on your skin type and treatment protocol.</td></tr>
</table>
$desc$, updated_at = now() where slug = 'isdin-fusion-water-magic-light-spf50';

-- 3. ISDIN Fusion Water Magic Medium SPF50
update public.products set description = $desc$
<h3>Is ISDIN Fusion Water Magic Medium right for you?</h3>
<ul>
<li><strong>Medium skin tones — the broadest range of South African complexions</strong> — The Medium shade is calibrated for Fitzpatrick types III–IV and suits the most common skin tone profiles seen in Dr. Bangalee's practice.</li>
<li><strong>Patients of Indian, mixed heritage or Mediterranean complexion</strong> — Provides the natural, skin-enhancing coverage that has historically been difficult to find in tinted SPF products designed primarily for pale European skin.</li>
<li><strong>Post-pigmentation treatment patients</strong> — Covers residual melasma or PIH marks while the SPF50 broad-spectrum protection prevents UV-triggered recurrence — a two-in-one daily treatment benefit.</li>
<li><strong>Patients wanting a simplified, one-product morning face routine</strong> — SPF50, light coverage and antioxidant protection in a water-light formula that takes under 30 seconds to apply.</li>
<li><strong>Active outdoor patients in a high-UV environment</strong> — The Fusion Water formula can be applied on wet skin for mid-activity reapplication — essential in KZN's year-round UV Index 10+ conditions.</li>
</ul>

<h3>How ISDIN Fusion Water Magic Medium works — the science</h3>
<p>The Medium variant delivers the full <strong>ISDIN Fusion Water technology</strong> platform — an ultra-fine aqueous suspension that encapsulates <strong>photostable SPF50 UVA and UVB filters</strong> in a water-phase vehicle that absorbs in seconds — combined with <strong>medium-tone mineral pigments</strong> specifically formulated to complement the range of complexions most common in South Africa's diverse population. The pigments are calibrated to deposit a sheer, adapting coverage that enhances rather than masks skin tone, with a warm-neutral undertone that avoids the grey or orange cast that plagues most medium-shade tinted SPFs. The <strong>antioxidant complex</strong> addresses the oxidative pathway of UV damage that topical SPF filters cannot fully prevent.</p>

<h3>What you will notice — and when</h3>
<p><strong>Immediately:</strong> A natural, even skin tone with a clean, non-greasy finish. The Medium tint adapts to blend seamlessly into a wide range of complexions without looking applied.<br><strong>Week 1–2:</strong> Morning routine simplifies. The combination of SPF and coverage in one step reduces the number of products layered on the face and cuts preparation time significantly.<br><strong>Month 1+:</strong> Consistent broad-spectrum UV protection prevents the UV-driven pigmentation that is particularly aggressive in medium-toned skin. Melasma and PIH patients maintain their treatment results significantly better with daily SPF50 compliance.</p>

<h3>How to use ISDIN Fusion Water Magic Medium</h3>
<ol>
<li>Apply after your morning skincare routine as the final step.</li>
<li>Dispense and apply evenly across the face, working outward from the centre. Blend well into the hairline and jaw to avoid a visible line.</li>
<li>Build lightly over any areas of discolouration by pressing with a fingertip rather than spreading — this concentrates the tint where needed.</li>
<li>Reapply every 2 hours. Apply directly onto wet or dry skin after swimming or exercise — no towelling off required before reapplication.</li>
</ol>

<h3>Key ingredients &amp; what they do</h3>
<table>
<tr><th>Ingredient</th><th>What it does for you</th></tr>
<tr><td>Fusion Water Technology</td><td>ISDIN's patented aqueous delivery system — distributes SPF filters and tint pigments in a water-light base that absorbs instantly without any oil residue or pore congestion.</td></tr>
<tr><td>Medium Shade Pigments</td><td>Warm-neutral cosmetic pigments calibrated for medium skin tones (Fitzpatrick III–IV) — provide sheer, naturally adapting coverage without grey cast or orange undertone.</td></tr>
<tr><td>SPF50 Broad-Spectrum Filters</td><td>Photostable UVA and UVB filters that provide consistent protection against the full UV spectrum — essential for medium skin tones where melasma and PIH are particularly common.</td></tr>
<tr><td>Antioxidant Complex</td><td>Targets the free radical cascade triggered by UV exposure — preventing the oxidative pathway of pigmentation that operates independently of the UV stimulus itself.</td></tr>
<tr><td>Hypoallergenic, Non-Comedogenic Base</td><td>Dermatologically tested vehicle free of comedogenic oils and common sensitisers — safe for daily use on all medium skin types including acne-prone and sensitive.</td></tr>
</table>

<h3>Dr. Bangalee's clinical perspective</h3>
<table>
<tr><td><strong>Dr. Bangalee Recommends</strong></td><td>"The Medium is the shade I prescribe most often in my practice — it suits the majority of my patients perfectly and gives them the coverage they need to feel confident while ensuring daily SPF50 compliance. For my pigmentation patients in particular, the combination of coverage and prevention in one product is genuinely valuable. They feel better about their skin immediately while the treatment protocol works in the background." — Dr. Rajeev Bangalee, MB BS</td></tr>
</table>

<h3>What our patients say</h3>
<table>
<tr>
<td>"I have a medium-toned complexion and tinted SPFs always made me look grey or orange. The Medium blends so naturally into my skin that my colleagues ask what foundation I am wearing." — Priya, 39</td>
<td>"Dr. Bangalee put me on this during my melasma protocol. The coverage hides the patches while the SPF stops them getting worse. I feel so much more confident going out." — Fatima, 43</td>
<td>"Lighter and more comfortable than anything else I have tried. I use this instead of foundation and SPF now — the whole routine is simpler and my skin looks better." — Zanele, 31</td>
</tr>
</table>

<h3>Frequently asked questions</h3>
<table>
<tr><td><strong>What skin tones does Medium suit?</strong></td><td>The Medium shade is calibrated for Fitzpatrick skin types III–IV — covering the broadest range of South African complexions including olive, Indian, mixed heritage and light brown skin tones. For fair skin, the Light variant is better matched. For deeper complexions, the Bronze is recommended.</td></tr>
<tr><td><strong>Is blue light protection included?</strong></td><td>The Fusion Water Magic filters cover UVA and UVB. Blue light and infrared protection are covered by ISDIN's Heliocare 360° range. For patients with active pigmentation where visible light is a trigger, Dr. Bangalee may recommend combining with Heliocare 360 Pigment Solution Fluid.</td></tr>
<tr><td><strong>Can I use this during active melasma treatment?</strong></td><td>Yes — this is exactly when it is most valuable. The SPF50 prevents UV-triggered darkening while treatment actives work to fade existing marks. The medium coverage conceals residual pigmentation and improves confidence during the treatment period.</td></tr>
<tr><td><strong>Does it need to be rubbed in completely?</strong></td><td>Yes — always blend thoroughly for both even coverage and consistent SPF protection. Patchy application leads to uneven colour and reduced sun protection where the product is too thin.</td></tr>
<tr><td><strong>Can I apply this on wet skin?</strong></td><td>Yes — the Fusion Water technology bonds to skin in the presence of water. This makes it the only tinted SPF you can reapply directly after a swim, a surf or a sweaty workout without needing to dry off first.</td></tr>
</table>
$desc$, updated_at = now() where slug = 'isdin-fusion-water-magic-medium-spf50';

-- 4. ISDIN Fusion Water Magic Bronze SPF50
update public.products set description = $desc$
<h3>Is ISDIN Fusion Water Magic Bronze right for you?</h3>
<ul>
<li><strong>Deeper skin tones tired of white cast and ashy finishes</strong> — The Bronze shade is ISDIN's answer to the longstanding failure of the SPF market to serve patients with deeper complexions adequately.</li>
<li><strong>Fitzpatrick types V–VI patients</strong> — Provides warm-toned coverage that enhances and complements rich, deep complexions — no grey cast, no ashiness, no colour distortion.</li>
<li><strong>Patients managing post-inflammatory hyperpigmentation (PIH)</strong> — Deeper skin tones are disproportionately affected by PIH after acne, Dermapen or any inflammatory event. The Bronze provides daily SPF50 protection to prevent UV from darkening marks while treatment actives work underneath.</li>
<li><strong>Patients who want a sun-kissed glow with full protection</strong> — The Bronze tint adds a naturally luminous warmth to lighter-medium skin tones too — a healthy, radiant finish with full broad-spectrum SPF.</li>
<li><strong>Active patients outdoors in KZN's year-round sun</strong> — Wet-skin application capability makes practical reapplication possible for the first time for outdoor and water activities.</li>
</ul>

<h3>How ISDIN Fusion Water Magic Bronze works — the science</h3>
<p>The Bronze formulation delivers the complete <strong>ISDIN Fusion Water technology platform</strong> with a <strong>rich bronze pigment complex</strong> specifically designed to complement deeper melanin-rich skin tones without the colour distortion that makes most conventional tinted SPFs unusable on dark skin. The pigments use a <strong>warm-toned base</strong> that avoids the grey undertone caused by titanium dioxide in mineral formulas and the orange drift common in poorly formulated tinted chemical sunscreens. <strong>SPF50 photostable UVA and UVB filters</strong> provide comprehensive protection against both sunburn and the deeper UV wavelengths that trigger melanin overproduction — particularly important in Fitzpatrick V–VI skin where PIH risk from UV is significantly elevated.</p>

<h3>What you will notice — and when</h3>
<p><strong>Immediately:</strong> A rich, warm finish that enhances and unifies your natural complexion. The Bronze tint looks applied-from-within rather than layered on top — zero white cast, zero ashiness.<br><strong>Week 1–2:</strong> Skin tone is more even throughout the day. Foundation use reduces or stops. Morning routine simplifies to one well-chosen product.<br><strong>Month 1+:</strong> Consistent SPF50 protection prevents the UV-triggered PIH episodes that are so difficult to treat in deeper skin tones. Existing marks fade faster when protected from UV aggravation daily.</p>

<h3>How to use ISDIN Fusion Water Magic Bronze</h3>
<ol>
<li>Apply as the final morning step after serum and any treatment products from Dr. Bangalee's protocol.</li>
<li>Blend evenly across the face using fingertips, working outward from the centre of the face. Pay attention to the jaw and hairline for a seamless finish.</li>
<li>For deeper coverage over specific marks, press additional product with a fingertip rather than spreading — this concentrates the bronze pigment where needed.</li>
<li>Reapply every 2 hours. The wet-skin application capability makes outdoor reapplication practical — apply directly after swimming or exercise without waiting to towel dry.</li>
</ol>

<h3>Key ingredients &amp; what they do</h3>
<table>
<tr><th>Ingredient</th><th>What it does for you</th></tr>
<tr><td>Fusion Water Technology</td><td>ISDIN's aqueous delivery system — distributes both SPF filters and bronze pigments in a water-light base that evaporates to deposit an even, luminous finish without any oil residue.</td></tr>
<tr><td>Bronze Tone Pigments</td><td>Warm-toned cosmetic pigments calibrated for deeper skin tones — enhance natural melanin richness without grey cast, ashiness or colour drift that affects other SPF products on dark skin.</td></tr>
<tr><td>SPF50 UVA/UVB Filters</td><td>Photostable broad-spectrum protection that guards against the UV-triggered melanin overproduction that drives post-inflammatory pigmentation in melanin-rich skin — the most common skin concern in Dr. Bangalee's deeper-toned patients.</td></tr>
<tr><td>Antioxidant Complex</td><td>Neutralises free radicals from UV and environmental exposure — a second line of defence against the oxidative pathway that independently triggers pigmentation in deep skin tones.</td></tr>
<tr><td>Hypoallergenic Non-Comedogenic Base</td><td>Oil-free vehicle that is non-comedogenic and dermatologically tested — delivers coverage without pore congestion, breakouts or the midday greasiness that affects many darker-toned patients in warm climates.</td></tr>
</table>

<h3>Dr. Bangalee's clinical perspective</h3>
<table>
<tr><td><strong>Dr. Bangalee Recommends</strong></td><td>"For my patients with deeper skin tones, finding an SPF they will actually wear consistently has historically been difficult — the white cast problem is real and I understand why patients avoid products that make their skin look grey. The Fusion Water Bronze solves this completely. It looks beautiful on deep skin and the SPF compliance improvement I see in patients who switch to it makes a meaningful difference to their outcomes." — Dr. Rajeev Bangalee, MB BS</td></tr>
</table>

<h3>What our patients say</h3>
<table>
<tr>
<td>"Every SPF I ever tried left me looking grey. The Bronze actually makes my skin glow. I wear it every day now and I have never done that with a sunscreen before." — Nomvula, 37</td>
<td>"I have dark skin and melasma. Dr. Bangalee prescribed this and it covers my patches beautifully while the SPF stops them getting worse. My confidence has come back." — Thandi, 42</td>
<td>"As someone with deep brown skin, this is the first tinted SPF I have found that actually looks like my skin. No more looking washed out or ashy." — Sipho, 33</td>
</tr>
</table>

<h3>Frequently asked questions</h3>
<table>
<tr><td><strong>Does it look natural on very dark skin tones?</strong></td><td>Yes — the Bronze is specifically calibrated to enhance and complement deep skin tones rather than cover them. The warm undertone avoids the grey or ashy look that is the most common complaint with SPF products on Fitzpatrick V–VI skin.</td></tr>
<tr><td><strong>Is SPF important for darker skin tones?</strong></td><td>Absolutely — while melanin provides some natural UV protection, it does not prevent photoageing, PIH or skin cancer. Darker skin tones are actually more prone to post-inflammatory hyperpigmentation triggered by UV exposure, making daily SPF50 compliance especially important.</td></tr>
<tr><td><strong>Can lighter skin tones use Bronze for a sun-kissed look?</strong></td><td>Yes — the Bronze adds a warm, radiant finish to medium skin tones too and is popular as a bronzing SPF for patients who want a healthy glow with full protection. Test on the inner wrist first to check the shade suits your tone.</td></tr>
<tr><td><strong>Can I apply this on wet skin?</strong></td><td>Yes — the Fusion Water technology bonds to skin even in the presence of water. Reapply directly after swimming or exercise without needing to dry off — the tinted protection layer is refreshed immediately.</td></tr>
<tr><td><strong>Does it transfer easily?</strong></td><td>The Fusion Water formula dries to a light-hold finish with minimal transfer. However, reapplication after mask wearing, extended phone use against the face, or prolonged contact with clothing is recommended.</td></tr>
</table>
$desc$, updated_at = now() where slug = 'isdin-fusion-water-magic-bronze-spf50';

-- 5. ISDIN UV Mineral Brush SPF50+
update public.products set description = $desc$
<h3>Is ISDIN UV Mineral Brush SPF50+ right for you?</h3>
<ul>
<li><strong>Anyone who wears makeup and has never found a practical way to reapply SPF</strong> — The UV Mineral Brush solves the single biggest compliance problem in sun protection: how to reapply over makeup without removing everything and starting again.</li>
<li><strong>Post-pigmentation treatment patients</strong> — Consistent midday reapplication is the difference between treatment results that hold and results that fade. The Brush makes twice-daily SPF application achievable for the first time.</li>
<li><strong>Office workers and commuters with outdoor exposure</strong> — Morning SPF degrades within 2 hours of direct sun exposure. The Brush in your bag or desk drawer means no sun protection gap during a lunchtime walk or outdoor commute.</li>
<li><strong>Sensitive skin patients including rosacea</strong> — The 100% mineral formula (zinc oxide + titanium dioxide) has zero sensitising potential — safe for the most reactive skin conditions even with multiple daily applications.</li>
<li><strong>Travellers and active patients</strong> — The twist-up brush design is mess-free, compact and TSA-compliant. The most portable SPF reapplication solution available.</li>
</ul>

<h3>How ISDIN UV Mineral Brush SPF50+ works — the science</h3>
<p>The UV Mineral Brush encapsulates <strong>100% mineral SPF filters — zinc oxide and titanium dioxide</strong> — in a ultra-fine pressed powder matrix suspended in the brush head. When applied over makeup, the powder <strong>deposits a fresh mineral filter layer</strong> directly onto the skin surface without disturbing the cosmetic products underneath — rebuilding the protective barrier that morning SPF loses to UV degradation, perspiration and environmental contact throughout the day. The <strong>mineral-only formula</strong> is inherently photostable and does not require chemical conversion of UV energy to heat — meaning it maintains full SPF50+ protection from application to the next reapplication without any degradation of the active layer. The <strong>universal shade powder base</strong> has a light mattifying effect that absorbs midday sebum and refreshes the complexion simultaneously.</p>

<h3>What you will notice — and when</h3>
<p><strong>Immediately:</strong> Apply over full makeup in 10 seconds. Skin looks freshened and mattified — not powdery, not heavy, not disrupted. SPF protection is fully restored.<br><strong>Daily use:</strong> Reapplying SPF midday stops being a theoretical obligation and becomes a 10-second routine you actually do. The Brush removes every practical barrier to adequate reapplication.<br><strong>Month 1+:</strong> Patients who genuinely achieve twice-daily SPF reapplication show measurably better outcomes from pigmentation and anti-ageing treatments — the cumulative UV that slips through a morning-only SPF routine is eliminated.</p>

<h3>How to use ISDIN UV Mineral Brush SPF50+</h3>
<ol>
<li>Apply morning liquid SPF as normal — the UV Mineral Brush is your reapplication tool, not your primary morning protection.</li>
<li>Twist the base to advance powder into the brush head. Tap gently to load the bristles.</li>
<li>Sweep generously and evenly across the full face — nose, forehead, cheekbones and chin receive the most UV exposure and need full coverage. Do not just dust lightly — apply with intent.</li>
<li>Reapply every 2 hours during sun exposure, or after any extended outdoor activity. One cartridge provides approximately 3 months of daily midday reapplication.</li>
</ol>

<h3>Key ingredients &amp; what they do</h3>
<table>
<tr><th>Ingredient</th><th>What it does for you</th></tr>
<tr><td>Zinc Oxide (mineral, 100%)</td><td>Broad-spectrum mineral filter that physically reflects both UVA and UVB radiation — inherently photostable, meaning it does not degrade with sun exposure and maintains full SPF50+ throughout the application period.</td></tr>
<tr><td>Titanium Dioxide (mineral)</td><td>Enhances UVB protection in combination with zinc oxide. Both are non-nano grade — safe for sensitive skin, rosacea and reactive conditions with zero sensitising potential.</td></tr>
<tr><td>Universal Shade Powder Base</td><td>Neutral-toned powder vehicle that adapts to most skin tones, provides light mattifying and coverage refresh without adding visible powder build-up or altering the makeup underneath.</td></tr>
<tr><td>Silica Spheres</td><td>Microsphere silica particles that absorb midday sebum and soft-focus the appearance of pores and fine lines — so reapplying SPF actually improves the complexion rather than disrupting it.</td></tr>
<tr><td>Ophthalmologically Tested Formula</td><td>Specifically tested safe for use around the eye area — can be applied over the delicate periocular skin that is disproportionately sun-exposed and often missed by liquid SPF reapplication.</td></tr>
</table>

<h3>Dr. Bangalee's clinical perspective</h3>
<table>
<tr><td><strong>Dr. Bangalee Recommends</strong></td><td>"The UV Mineral Brush is one of the most practically impactful products I recommend. I know from experience that patients apply their morning SPF and then do not reapply — and for pigmentation patients especially, that gap in the afternoon is where UV exposure does its damage. The Brush removes every excuse not to reapply. I give it to every pigmentation and anti-ageing patient and ask them to keep it at their desk or in their bag without exception." — Dr. Rajeev Bangalee, MB BS</td></tr>
</table>

<h3>What our patients say</h3>
<table>
<tr>
<td>"I have been treating my melasma for six months and Dr. Bangalee credits the Brush with why my results have held so well. I reapply at lunch every day — it takes 10 seconds and my makeup still looks perfect." — Sunita, 44</td>
<td>"I keep this at my desk at work. Quick sweep at lunchtime, no mess, no disrupting my makeup. It has become completely automatic. I cannot believe I used to skip reapplication." — Karen, 39</td>
<td>"As someone who travels constantly, this is the most useful skincare product I own. Compact, clean, no spills, works over everything. Essential in my carry-on." — Warren, 47</td>
</tr>
</table>

<h3>Frequently asked questions</h3>
<table>
<tr><td><strong>Can I use this as my only morning SPF?</strong></td><td>No — the UV Mineral Brush is engineered for reapplication over an existing SPF base. Apply a full liquid SPF (such as ISDIN Fusion Water Magic SPF50) as your morning protection and use the Brush for midday and afternoon top-ups.</td></tr>
<tr><td><strong>Does the powder look cakey over makeup?</strong></td><td>No — when applied as directed (generous sweep rather than heavy build-up), the powder deposits a light, refreshing layer that mattifies and sets existing makeup rather than sitting on top of it. The silica spheres give a soft-focus rather than a powdery result.</td></tr>
<tr><td><strong>Is it suitable for sensitive skin and rosacea?</strong></td><td>Yes — the 100% mineral formula is the gentlest available SPF format. It contains no chemical filters that can trigger flushing or sensitisation in reactive conditions. Safe for daily multiple-application use on rosacea-prone skin.</td></tr>
<tr><td><strong>How does this compare to the Heliocare Compacts SPF50?</strong></td><td>Both are powder SPF reapplication tools for use over makeup. The ISDIN UV Mineral Brush uses 100% mineral filters (ideal for sensitive/reactive skin) and features a built-in brush for precise application. The Heliocare Compacts use a combination formula. Dr. Bangalee will recommend based on your skin type and treatment protocol.</td></tr>
<tr><td><strong>How long does one cartridge last?</strong></td><td>With one daily midday application to the face, a cartridge lasts approximately 3 months. If you reapply twice daily (recommended for high-sun-exposure patients and those on pigmentation protocols), budget for 6 weeks per cartridge.</td></tr>
</table>
$desc$, updated_at = now() where slug = 'isdin-uv-mineral-brush-spf50';

-- ══════════════════════════════════════════════════════════
-- VERIFY
-- ══════════════════════════════════════════════════════════
select
  name,
  case when description like '%Dr. Bangalee%' then '✅ HAS DR B' else '❌ MISSING' end as dr_b,
  case when description like '%patients say%' then '✅ HAS TESTIMONIALS' else '❌ MISSING' end as testimonials,
  case when description like '%asked questions%' then '✅ HAS FAQ' else '❌ MISSING' end as faq,
  length(description) as desc_chars,
  case when length(description) > 3000 then 'OK' else 'TOO SHORT' end as length_check
from public.products
where brand_slug = 'isdin'
order by name;
